### ISSUE TITLE
TypeError: User.hasMany is not a function

### ISSUE THREAD

**Issue by mariantatarau** [festo/sails-hook-sequelize#5]
TypeError: User.hasMany is not a function
    at Object.User.associations (/srv/http/myapp/api/models/User.js:82:8)
    at Hook.setAssociation (/srv/http/myapp/node_modules/sails-hook-sequelize/index.js:72:20)
    at Hook.bound [as setAssociation] (/srv/http/myapp/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at /srv/http/myapp/node_modules/sails-hook-sequelize/index.js:41:16
    at /srv/http/myapp/node_modules/sails/lib/hooks/moduleloader/index.js:294:18
    at /srv/http/myapp/node_modules/sails/lib/hooks/moduleloader/index.js:499:14
    at buildDictionary (/srv/http/myapp/node_modules/sails-build-dictionary/index.js:134:9)
    at Function.module.exports.optional (/srv/http/myapp/node_modules/sails-build-dictionary/index.js:160:9)
    at /srv/http/myapp/node_modules/sails/lib/hooks/moduleloader/index.js:287:25
    at buildDictionary (/srv/http/myapp/node_modules/sails-build-dictionary/index.js:134:9)
    at Function.module.exports.optional (/srv/http/myapp/node_modules/sails-build-dictionary/index.js:160:9)
    at Hook.loadModels (/srv/http/myapp/node_modules/sails/lib/hooks/moduleloader/index.js:279:23)
    at Hook.bound [as loadModels] (/srv/http/myapp/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at Hook.initialize (/srv/http/myapp/node_modules/sails-hook-sequelize/index.js:26:28)
    at Hook.bound [as initialize] (/srv/http/myapp/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at /srv/http/myapp/node_modules/sails/lib/hooks/index.js:75:14
    at /srv/http/myapp/node_modules/sails/node_modules/async/lib/async.js:451:17
    at /srv/http/myapp/node_modules/sails/node_modules/async/lib/async.js:441:17
    at _each (/srv/http/myapp/node_modules/sails/node_modules/async/lib/async.js:46:13)
    at Immediate.taskComplete (/srv/http/myapp/node_modules/sails/node_modules/async/lib/async.js:440:13)
    at Immediate._onImmediate (/srv/http/myapp/node_modules/async-listener/glue.js:188:31)
    at processImmediate [as _immediateCallback] (timers.js:374:17)

**Comment by festo** [comment]
I think the bug is not connected to the project, something wrong your User model.

**Comment by ragranados** [comment]
I have the same problem, but its inly happening with User model, other models work great
